version: '3.4'

services:
  sut:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    image:
      debos-builder
    working_dir: /usr/local/go/src/github.com/akaybayram61/debos-minimal
    command: go test -v ./...
